#!/bin/bash
set -euo pipefail
echo "==== Conversation-only recording (start on agent answer) ===="
B_IN='LS0gUmluZyB0aGUgbG9uZ2VzdC1pZGxlIFJlYWR5IHJlZ2lzdGVyZWQgYWdlbnQgd2hvIGlzIG5vdCBhbHJlYWR5IG9uIGEgY2FsbC4KLS0gRGVjbGluZSBlbmRzIHRoaXMgY3VzdG9tZXIgY2FsbCAoZG9lcyBub3Qgcm9sbCB0byB0aGUgbmV4dCBhZ2VudCkuCi0tIElmIGV2ZXJ5IFJlYWR5IGFnZW50IGlzIGJ1c3ksIHBhcmsgaW4gY2FsbGNlbnRlciBzbyB0aGUgY2FsbGVyIHdhaXRzLgppZiBub3Qgc2Vzc2lvbiB0aGVuCiAgcmV0dXJuCmVuZAoKbG9jYWwgYXBpID0gZnJlZXN3aXRjaC5BUEkoKQpsb2NhbCBkb21haW4gPSBzZXNzaW9uOmdldFZhcmlhYmxlKCJkb21haW5fbmFtZSIpIG9yICJjbGllbnQxLnNreWtpbi5sb2NhbCIKbG9jYWwgY2lkID0gc2Vzc2lvbjpnZXRWYXJpYWJsZSgiY2FsbGVyX2lkX251bWJlciIpCiAgICBvciBzZXNzaW9uOmdldFZhcmlhYmxlKCJhbmkiKQogICAgb3Igc2Vzc2lvbjpnZXRWYXJpYWJsZSgic2lwX2Zyb21fdXNlciIpCiAgICBvciBzZXNzaW9uOmdldFZhcmlhYmxlKCJlZmZlY3RpdmVfY2FsbGVyX2lkX251bWJlciIpCiAgICBvciBzZXNzaW9uOmdldFZhcmlhYmxlKCJzaXBfcF9hc3NlcnRlZF9pZGVudGl0eSIpCiAgICBvciBzZXNzaW9uOmdldFZhcmlhYmxlKCJzaXBfY2lkX251bSIpCiAgICBvciAiIgppZiBzZXNzaW9uOmdldFZhcmlhYmxlKCJza3lraW5fYmxvY2tlZCIpID09ICJ0cnVlIiBvciBub3Qgc2Vzc2lvbjpyZWFkeSgpIHRoZW4KICBzZXNzaW9uOmV4ZWN1dGUoImhhbmd1cCIsICJDQUxMX1JFSkVDVEVEIikKICByZXR1cm4KZW5kCmxvY2FsIGZ1bmN0aW9uIGJsX2RpZ2l0cyhzKQogIHMgPSAocyBvciAiIik6Z3N1YigiJUQiLCAiIikKICBpZiBzOnN1YigxLCAzKSA9PSAiMjUxIiBhbmQgI3MgPj0gMTIgdGhlbiBzID0gczpzdWIoNCkgZW5kCiAgaWYgI3MgPT0gMTAgYW5kIHM6c3ViKDEsIDEpID09ICIwIiB0aGVuIHMgPSBzOnN1YigyKSBlbmQKICByZXR1cm4gcwplbmQKbG9jYWwgZnVuY3Rpb24gYmxfZmlsZV9oaXQod2FudCwgcGF0aCkKICBpZiBkb21haW4gPT0gIiIgdGhlbiByZXR1cm4gZmFsc2UgZW5kCiAgbG9jYWwgZiA9IGlvLm9wZW4ocGF0aCwgInIiKQogIGlmIG5vdCBmIHRoZW4gcmV0dXJuIGZhbHNlIGVuZAogIGZvciBsaW5lIGluIGY6bGluZXMoKSBkbwogICAgaWYgbGluZTpzdWIoMSwgMSkgfj0gIiMiIGFuZCBsaW5lIH49ICIiIHRoZW4KICAgICAgbG9jYWwgYSwgYiA9IGxpbmU6bWF0Y2goIl4oW158XSspfChbXnxdKykiKQogICAgICBpZiBhID09IGRvbWFpbiB0aGVuCiAgICAgICAgbG9jYWwgbiA9IGJsX2RpZ2l0cyhiIG9yICIiKQogICAgICAgIGlmIG4gfj0gIiIgdGhlbgogICAgICAgICAgbG9jYWwgayA9IG1hdGgubWluKCN3YW50LCAjbiwgMTIpCiAgICAgICAgICBpZiBrID49IDcgYW5kIHdhbnQ6c3ViKC1rKSA9PSBuOnN1YigtaykgdGhlbgogICAgICAgICAgICBmOmNsb3NlKCkKICAgICAgICAgICAgcmV0dXJuIHRydWUKICAgICAgICAgIGVuZAogICAgICAgIGVuZAogICAgICBlbmQKICAgIGVuZAogIGVuZAogIGY6Y2xvc2UoKQogIHJldHVybiBmYWxzZQplbmQKbG9jYWwgZnVuY3Rpb24gYmxhY2tsaXN0ZWQoKQogIGxvY2FsIHdhbnQgPSBibF9kaWdpdHMoY2lkKQogIGlmICN3YW50IDwgNyBvciBkb21haW4gPT0gIiIgdGhlbiByZXR1cm4gZmFsc2UgZW5kCiAgbG9jYWwga2V5cyA9IHsgd2FudCwgd2FudDpzdWIoLTkpLCB3YW50OnN1YigtOCksIHdhbnQ6c3ViKC03KSwgIjI1MSIgLi4gd2FudCwgIjAiIC4uIHdhbnQgfQogIGZvciBfLCBrZXkgaW4gaXBhaXJzKGtleXMpIGRvCiAgICBpZiAja2V5ID49IDcgdGhlbgogICAgICBsb2NhbCBoID0gYXBpOmV4ZWN1dGUoImhhc2giLCAic2VsZWN0L3NreWtpbl9ibC8iIC4uIGRvbWFpbiAuLiAifiIgLi4ga2V5KSBvciAiIgogICAgICBoID0gaDpnc3ViKCIlcyskIiwgIiIpCiAgICAgIGlmIGggPT0gIjEiIG9yIGg6bWF0Y2goIl4xJXMiKSB0aGVuCiAgICAgICAgcmV0dXJuIHRydWUKICAgICAgZW5kCiAgICBlbmQKICBlbmQKICByZXR1cm4gYmxfZmlsZV9oaXQod2FudCwgIi9ldGMvZnJlZXN3aXRjaC9zY3JpcHRzL3NreWtpbl9ibGFja2xpc3QudHh0IikKICAgICAgb3IgYmxfZmlsZV9oaXQod2FudCwgIi92YXIvbGliL2ZyZWVzd2l0Y2gvcmVjb3JkaW5ncy9za3lraW5fYmxhY2tsaXN0LnR4dCIpCmVuZAppZiBibGFja2xpc3RlZCgpIHRoZW4KICBmcmVlc3dpdGNoLmNvbnNvbGVMb2coIk5PVElDRSIsICJza3lraW4gYmxhY2tsaXN0IGRyb3AgY2lkPSIgLi4gY2lkIC4uICJcbiIpCiAgc2Vzc2lvbjpzZXRWYXJpYWJsZSgiY29udGludWVfb25fZmFpbCIsICJmYWxzZSIpCiAgc2Vzc2lvbjpzZXRWYXJpYWJsZSgic2t5a2luX2Jsb2NrZWQiLCAidHJ1ZSIpCiAgc2Vzc2lvbjpleGVjdXRlKCJoYW5ndXAiLCAiQ0FMTF9SRUpFQ1RFRCIpCiAgZXJyb3IoInNreWtpbiBibG9ja2VkIikKZW5kCgpsb2NhbCBxdWV1ZSA9ICI4MDAwQCIgLi4gZG9tYWluCmxvY2FsIHJ0cF9pcCA9ICIxOTYuMTg5LjIzNi4xNDAiCgpzZXNzaW9uOmV4ZWN1dGUoInJpbmdfcmVhZHkiKQpzZXNzaW9uOnNldFZhcmlhYmxlKCJoYW5ndXBfYWZ0ZXJfYnJpZGdlIiwgInRydWUiKQpzZXNzaW9uOnNldFZhcmlhYmxlKCJjb250aW51ZV9vbl9mYWlsIiwgInRydWUiKQpzZXNzaW9uOnNldFZhcmlhYmxlKCJpZ25vcmVfZWFybHlfbWVkaWEiLCAidHJ1ZSIpCnNlc3Npb246c2V0VmFyaWFibGUoImJyaWRnZV9lYXJseV9tZWRpYSIsICJmYWxzZSIpCgotLSBDb252ZXJzYXRpb24tb25seSByZWNvcmRpbmc6IG5ldmVyIHN0YXJ0IG9uIElWUiBhbnN3ZXIuCnNlc3Npb246c2V0VmFyaWFibGUoImV4ZWN1dGVfb25fYW5zd2VyIiwgIiIpCnNlc3Npb246c2V0VmFyaWFibGUoInJlY29yZF9zdGVyZW8iLCAidHJ1ZSIpCnNlc3Npb246c2V0VmFyaWFibGUoIlJFQ09SRF9TVEVSRU8iLCAidHJ1ZSIpCnNlc3Npb246c2V0VmFyaWFibGUoInJlY29yZGluZ19mb2xsb3dfdHJhbnNmZXIiLCAidHJ1ZSIpCgpsb2NhbCBmdW5jdGlvbiBlbnN1cmVfcmVjb3JkX3ZhcnMoKQogIGxvY2FsIGRvbWFpbl9uYW1lID0gc2Vzc2lvbjpnZXRWYXJpYWJsZSgiZG9tYWluX25hbWUiKSBvciBkb21haW4KICBsb2NhbCBwYXRoID0gc2Vzc2lvbjpnZXRWYXJpYWJsZSgicmVjb3JkX3BhdGgiKSBvciAiIgogIGxvY2FsIG5hbWUgPSBzZXNzaW9uOmdldFZhcmlhYmxlKCJyZWNvcmRfbmFtZSIpIG9yICIiCiAgaWYgcGF0aCA9PSAiIiBvciBwYXRoOmZpbmQoIiV7IiwgMSwgdHJ1ZSkgb3IgcGF0aDpmaW5kKCIkeyIsIDEsIHRydWUpIHRoZW4KICAgIGxvY2FsIHkgPSAoYXBpOmV4ZWN1dGUoInN0cmZ0aW1lIiwgIiVZIikgb3IgIjIwMjYiKTpnc3ViKCIlcysiLCAiIikKICAgIGxvY2FsIG1vbiA9IChhcGk6ZXhlY3V0ZSgic3RyZnRpbWUiLCAiJWIiKSBvciAiSmFuIik6Z3N1YigiJXMrIiwgIiIpCiAgICBsb2NhbCBkID0gKGFwaTpleGVjdXRlKCJzdHJmdGltZSIsICIlZCIpIG9yICIwMSIpOmdzdWIoIiVzKyIsICIiKQogICAgcGF0aCA9ICIvdmFyL2xpYi9mcmVlc3dpdGNoL3JlY29yZGluZ3MvIiAuLiBkb21haW5fbmFtZQogICAgICAuLiAiL2FyY2hpdmUvIiAuLiB5IC4uICIvIiAuLiBtb24gLi4gIi8iIC4uIGQKICAgIHNlc3Npb246c2V0VmFyaWFibGUoInJlY29yZF9wYXRoIiwgcGF0aCkKICBlbmQKICBpZiBuYW1lID09ICIiIHRoZW4KICAgIG5hbWUgPSAoc2Vzc2lvbjpnZXRWYXJpYWJsZSgidXVpZCIpIG9yICJjYWxsIikgLi4gIi53YXYiCiAgICBzZXNzaW9uOnNldFZhcmlhYmxlKCJyZWNvcmRfbmFtZSIsIG5hbWUpCiAgZW5kCiAgYXBpOmV4ZWN1dGUoInN5c3RlbSIsICJta2RpciAtcCAnIiAuLiBwYXRoIC4uICInIikKICByZXR1cm4gcGF0aCAuLiAiLyIgLi4gbmFtZQplbmQKCmxvY2FsIGZ1bmN0aW9uIGFnZW50X2JyaWRnZV9zdHJpbmcoZGVzdCwgcmVjX2ZpbGUsIGFfdXVpZCkKICAtLSBTdGFydCBBLWxlZyByZWNvcmRpbmcgb25seSB3aGVuIHRoZSBhZ2VudCBCLWxlZyBhbnN3ZXJzIChub3QgZHVyaW5nIElWUikuCiAgbG9jYWwgb25fYW5zd2VyID0gImx1YSAvZXRjL2ZyZWVzd2l0Y2gvc2NyaXB0cy9za3lraW5fcmVjb3JkX29uX2FnZW50Lmx1YSAiCiAgICAuLiBhX3V1aWQgLi4gIiAiIC4uIHJlY19maWxlCiAgcmV0dXJuICJ7aWdub3JlX2Vhcmx5X21lZGlhPXRydWUsYnJpZGdlX2Vhcmx5X21lZGlhPWZhbHNlLG9yaWdpbmF0ZV90aW1lb3V0PTQ1LCIKICAgIC4uICJhcGlfb25fYW5zd2VyPSciIC4uIG9uX2Fuc3dlciAuLiAiJ30iCiAgICAuLiAiW2xlZ190aW1lb3V0PTMwLG1lZGlhX3dlYnJ0Yz10cnVlLHJ0cF9zZWN1cmVfbWVkaWE9b3B0aW9uYWwscnRwX2FkdmVydGlzZV9pcD0iCiAgICAuLiBydHBfaXAgLi4gIixpbmNsdWRlX2V4dGVybmFsX2lwPXRydWVddXNlci8iIC4uIGRlc3QgLi4gIkAiIC4uIGRvbWFpbgplbmQKCmxvY2FsIGZ1bmN0aW9uIGNvbHMobGluZSkKICBsb2NhbCBjID0ge30KICBmb3IgeCBpbiAobGluZSAuLiAifCIpOmdtYXRjaCgiKC4tKXwiKSBkbyBjWyNjICsgMV0gPSB4IGVuZAogIHJldHVybiBjCmVuZAoKbG9jYWwgZnVuY3Rpb24gcmVnaXN0ZXJlZChleHQpCiAgbG9jYWwgciA9IGFwaTpleGVjdXRlKCJzb2ZpYV9jb250YWN0IiwgIiovIiAuLiBleHQgLi4gIkAiIC4uIGRvbWFpbikgb3IgIiIKICBpZiByOmZpbmQoImVycm9yIiwgMSwgdHJ1ZSkgb3IgcjpmaW5kKCJ1c2VyX25vdF9yZWdpc3RlcmVkIiwgMSwgdHJ1ZSkgdGhlbgogICAgcmV0dXJuIGZhbHNlCiAgZW5kCiAgcmV0dXJuIHI6ZmluZCgic2lwOiIsIDEsIHRydWUpIH49IG5pbAplbmQKCmxvY2FsIGZ1bmN0aW9uIG9uX2FfY2FsbChleHQpCiAgbG9jYWwgY2hhbnMgPSBhcGk6ZXhlY3V0ZSgic2hvdyIsICJjaGFubmVscyIpIG9yICIiCiAgcmV0dXJuIGNoYW5zOmZpbmQoInVzZXIvIiAuLiBleHQgLi4gIkAiIC4uIGRvbWFpbiwgMSwgdHJ1ZSkgfj0gbmlsCiAgICAgIG9yIGNoYW5zOmZpbmQoIi8iIC4uIGV4dCAuLiAiQCIgLi4gZG9tYWluLCAxLCB0cnVlKSB+PSBuaWwKZW5kCgpsb2NhbCBmdW5jdGlvbiByZWFkeV9hZ2VudHMoc2tpcCkKICBsb2NhbCBvdXQgPSBhcGk6ZXhlY3V0ZSgiY2FsbGNlbnRlcl9jb25maWciLCAicXVldWUgbGlzdCBhZ2VudHMgIiAuLiBxdWV1ZSkgb3IgIiIKICBsb2NhbCByb3dzID0ge30KICBmb3IgbGluZSBpbiBvdXQ6Z21hdGNoKCJbXlxyXG5dKyIpIGRvCiAgICBpZiBsaW5lOmZpbmQoInwiLCAxLCB0cnVlKSBhbmQgbGluZTpzdWIoMSwgNSkgfj0gIm5hbWV8IiB0aGVuCiAgICAgIGxvY2FsIGMgPSBjb2xzKGxpbmUpCiAgICAgIGxvY2FsIGV4dCA9IChjWzVdIG9yICIiKTptYXRjaCgidXNlci8oW15AXSspIikKICAgICAgbG9jYWwgc3RhdHVzLCBzdGF0ZSA9IGNbNl0gb3IgIiIsIGNbN10gb3IgIiIKICAgICAgaWYgZXh0IGFuZCBub3Qgc2tpcFtleHRdCiAgICAgICAgICBhbmQgc3RhdHVzID09ICJBdmFpbGFibGUiIGFuZCAoc3RhdGUgPT0gIldhaXRpbmciIG9yIHN0YXRlID09ICJJZGxlIikKICAgICAgICAgIGFuZCByZWdpc3RlcmVkKGV4dCkgYW5kIG5vdCBvbl9hX2NhbGwoZXh0KSB0aGVuCiAgICAgICAgcm93c1sjcm93cyArIDFdID0geyBleHQgPSBleHQsIGlkbGUgPSB0b251bWJlcihjWzIwXSkgb3IgdG9udW1iZXIoY1sxNF0pIG9yIDAgfQogICAgICBlbmQKICAgIGVuZAogIGVuZAogIHRhYmxlLnNvcnQocm93cywgZnVuY3Rpb24oYSwgYikgcmV0dXJuIGEuaWRsZSA8IGIuaWRsZSBlbmQpCiAgcmV0dXJuIHJvd3MKZW5kCgpsb2NhbCByZWNfZmlsZSA9IGVuc3VyZV9yZWNvcmRfdmFycygpCmxvY2FsIGFfdXVpZCA9IHNlc3Npb246Z2V0VmFyaWFibGUoInV1aWQiKSBvciAiIgoKbG9jYWwgc2tpcCA9IHt9CndoaWxlIHNlc3Npb246cmVhZHkoKSBkbwogIGxvY2FsIGFnZW50cyA9IHJlYWR5X2FnZW50cyhza2lwKQogIGxvY2FsIGRlc3QgPSBhZ2VudHNbMV0gYW5kIGFnZW50c1sxXS5leHQKICBpZiBub3QgZGVzdCB0aGVuCiAgICBmcmVlc3dpdGNoLmNvbnNvbGVMb2coIk5PVElDRSIsICJza3lraW4gaW5ib3VuZCBxdWV1ZSB3YWl0ICIgLi4gcXVldWUgLi4gIlxuIikKICAgIC0tIFF1ZXVlIHJlY29yZHMgb25seSBhZnRlciBhbiBhZ2VudCBhbnN3ZXJzIChyZWNvcmQtdGVtcGxhdGUgb24gcXVldWUpLgogICAgc2Vzc2lvbjpzZXRWYXJpYWJsZSgiZXhlY3V0ZV9vbl9hbnN3ZXIiLCAiIikKICAgIHNlc3Npb246ZXhlY3V0ZSgiY2FsbGNlbnRlciIsIHF1ZXVlKQogICAgcmV0dXJuCiAgZW5kCiAgbG9jYWwgYnJpZGdlID0gYWdlbnRfYnJpZGdlX3N0cmluZyhkZXN0LCByZWNfZmlsZSwgYV91dWlkKQogIGZyZWVzd2l0Y2guY29uc29sZUxvZygiTk9USUNFIiwgInNreWtpbiBpbmJvdW5kIHRyeSAiIC4uIGRlc3QgLi4gIkAiIC4uIGRvbWFpbgogICAgLi4gIiByZWM9IiAuLiByZWNfZmlsZSAuLiAiXG4iKQogIHNlc3Npb246ZXhlY3V0ZSgiYnJpZGdlIiwgYnJpZGdlKQogIGlmIG5vdCBzZXNzaW9uOnJlYWR5KCkgdGhlbgogICAgcmV0dXJuCiAgZW5kCiAgbG9jYWwgb2ssIGFuc3dlcmVkID0gcGNhbGwoZnVuY3Rpb24oKSByZXR1cm4gc2Vzc2lvbjphbnN3ZXJlZCgpIGVuZCkKICBpZiBvayBhbmQgYW5zd2VyZWQgdGhlbgogICAgcmV0dXJuCiAgZW5kCiAgbG9jYWwgY2F1c2UgPSBzdHJpbmcudXBwZXIoc2Vzc2lvbjpnZXRWYXJpYWJsZSgibGFzdF9icmlkZ2VfaGFuZ3VwX2NhdXNlIikKICAgICAgb3Igc2Vzc2lvbjpnZXRWYXJpYWJsZSgib3JpZ2luYXRlX2Rpc3Bvc2l0aW9uIikgb3IgIiIpCiAgbG9jYWwgc2lwID0gc2Vzc2lvbjpnZXRWYXJpYWJsZSgic2lwX2ludml0ZV9mYWlsdXJlX3N0YXR1cyIpIG9yICIiCiAgZnJlZXN3aXRjaC5jb25zb2xlTG9nKCJOT1RJQ0UiLCAic2t5a2luIGluYm91bmQgY2F1c2U9IiAuLiBjYXVzZQogICAgLi4gIiBzaXA9IiAuLiBzaXAgLi4gIiBkZXN0PSIgLi4gZGVzdCAuLiAiXG4iKQogIGlmIHNpcCA9PSAiNDg2IiBvciBjYXVzZTpmaW5kKCJVU0VSX0JVU1kiLCAxLCB0cnVlKQogICAgICBvciBjYXVzZTpmaW5kKCJOT19BTlNXRVIiLCAxLCB0cnVlKSBvciBjYXVzZTpmaW5kKCJBTExPVFRFRCIsIDEsIHRydWUpCiAgICAgIG9yIGNhdXNlOmZpbmQoIlVTRVJfTk9UX1JFR0lTVEVSRUQiLCAxLCB0cnVlKSBvciBzaXAgPT0gIjQwOCIgdGhlbgogICAgc2tpcFtkZXN0XSA9IHRydWUKICAgIHNlc3Npb246c2xlZXAoMjAwKQogIGVsc2UKICAgIGZyZWVzd2l0Y2guY29uc29sZUxvZygiTk9USUNFIiwgInNreWtpbiBpbmJvdW5kIGRlY2xpbmUgZHJvcCBkZXN0PSIgLi4gZGVzdCAuLiAiXG4iKQogICAgc2Vzc2lvbjpoYW5ndXAoIk5PUk1BTF9DTEVBUklORyIpCiAgICByZXR1cm4KICBlbmQKZW5kCg=='
B_RE='LS0gU3RhcnQgc3RlcmVvIHJlY29yZGluZyBvbiB0aGUgY2FsbGVyIChBLWxlZykgd2hlbiB0aGUgYWdlbnQgKEItbGVnKSBhbnN3ZXJzLg0KLS0gVXNlZCB2aWEgYXBpX29uX2Fuc3dlciBvbiB0aGUgYWdlbnQgb3JpZ2luYXRlIHNvIElWUi9vcGVuaW5nIGlzIG5ldmVyIHJlY29yZGVkLg0KLS0gQXJnczogPGEtdXVpZD4gPGZ1bGwtd2F2LXBhdGg+DQpsb2NhbCBhcGkgPSBmcmVlc3dpdGNoLkFQSSgpDQpsb2NhbCBhX3V1aWQgPSBhcmd2WzFdIG9yICIiDQpsb2NhbCBmaWxlID0gYXJndlsyXSBvciAiIg0KaWYgYV91dWlkID09ICIiIG9yIGZpbGUgPT0gIiIgdGhlbg0KICBmcmVlc3dpdGNoLmNvbnNvbGVMb2coIldBUk5JTkciLCAic2t5a2luX3JlY29yZF9vbl9hZ2VudCBtaXNzaW5nIHV1aWQvZmlsZVxuIikNCiAgcmV0dXJuDQplbmQNCi0tIEVuc3VyZSBwYXJlbnQgZGlyIGV4aXN0cy4NCmxvY2FsIGRpciA9IGZpbGU6bWF0Y2goIiguKykvW14vXSskIikNCmlmIGRpciBhbmQgZGlyIH49ICIiIHRoZW4NCiAgYXBpOmV4ZWN1dGUoInN5c3RlbSIsICJta2RpciAtcCAnIiAuLiBkaXIgLi4gIiciKQ0KZW5kDQphcGk6ZXhlY3V0ZSgidXVpZF9zZXR2YXIiLCBhX3V1aWQgLi4gIiBSRUNPUkRfU1RFUkVPIHRydWUiKQ0KYXBpOmV4ZWN1dGUoInV1aWRfc2V0dmFyIiwgYV91dWlkIC4uICIgcmVjb3JkaW5nX2ZvbGxvd190cmFuc2ZlciB0cnVlIikNCmxvY2FsIHJlcyA9IGFwaTpleGVjdXRlKCJ1dWlkX3JlY29yZCIsIGFfdXVpZCAuLiAiIHN0YXJ0ICIgLi4gZmlsZSkgb3IgIiINCmZyZWVzd2l0Y2guY29uc29sZUxvZygiTk9USUNFIiwgInNreWtpbl9yZWNvcmRfb25fYWdlbnQgc3RhcnQgIiAuLiBhX3V1aWQNCiAgLi4gIiAtPiAiIC4uIGZpbGUgLi4gIiByZXM9IiAuLiB0b3N0cmluZyhyZXMpIC4uICJcbiIpDQo='
echo "$B_IN" | base64 -d > /tmp/skykin_inbound.lua
echo "$B_RE" | base64 -d > /tmp/skykin_record_on_agent.lua

# Install into FreeSWITCH container
docker cp /tmp/skykin_inbound.lua skykin-freeswitch:/etc/freeswitch/scripts/skykin_inbound.lua
docker cp /tmp/skykin_record_on_agent.lua skykin-freeswitch:/etc/freeswitch/scripts/skykin_record_on_agent.lua

# Persist for container recreate
mkdir -p /opt/skykin/fs-live
cp -f /tmp/skykin_inbound.lua /opt/skykin/fs-live/skykin_inbound.lua
cp -f /tmp/skykin_record_on_agent.lua /opt/skykin/fs-live/skykin_record_on_agent.lua

# Stop recording on IVR answer in live DID dialplans
python3 - <<'PY'
from pathlib import Path
import subprocess
cands = [
  "/opt/skykin/fs-live/02_skykin_did_ahununu.xml",
  "/opt/skykin/fs-live/01_skykin_did.xml",
]
# Also pull from container if live copies missing
for remote in (
  "/etc/freeswitch/dialplan/public/02_skykin_did_ahununu.xml",
  "/etc/freeswitch/dialplan/public/01_skykin_did.xml",
):
  local = "/tmp/" + Path(remote).name
  subprocess.run(["docker","cp", f"skykin-freeswitch:{remote}", local], check=False)
  if Path(local).exists():
    cands.append(local)

seen=set()
for p in cands:
  path=Path(p)
  if not path.exists() or str(path) in seen:
    continue
  seen.add(str(path))
  t=path.read_text(encoding="utf-8", errors="replace")
  old=t
  t=t.replace(
    'execute_on_answer=record_session ${record_path}/${record_name}',
    'execute_on_answer='
  )
  t=t.replace(
    'execute_on_answer=record_session \${record_path}/\${record_name}',
    'execute_on_answer='
  )
  # common XML forms
  import re
  t=re.sub(
    r'<action application="set" data="execute_on_answer=record_session[^"]*"/>',
    '<action application="set" data="execute_on_answer="/>',
    t
  )
  if t!=old:
    path.write_text(t, encoding="utf-8")
    print("patched", path)
    # push back into container public dialplan when tmp
    name=path.name
    if name.startswith("0"):
      subprocess.run(["docker","cp", str(path), f"skykin-freeswitch:/etc/freeswitch/dialplan/public/{name}"], check=False)
      live=Path("/opt/skykin/fs-live")/name
      live.write_text(t, encoding="utf-8")
      print("saved", live)
  else:
    print("no record-on-answer change", path)
PY

# Callcenter: record only after agent answers
python3 - <<'PY'
from pathlib import Path
import subprocess
for src,dst in [
  ("skykin-freeswitch:/etc/freeswitch/autoload_configs/callcenter.conf.xml", "/tmp/callcenter.conf.xml"),
]:
  subprocess.run(["docker","cp", src, dst], check=False)
p=Path("/tmp/callcenter.conf.xml")
if p.exists():
  t=p.read_text(encoding="utf-8", errors="replace")
  if "record-template" not in t:
    t=t.replace(
      '<param name="moh-sound" value=""/>',
      '<param name="moh-sound" value=""/>\n      <param name="record-template" value="${record_path}/${record_name}"/>',
      1
    )
    # only first queue may have been updated; do all moh-sound lines
    if t.count("record-template") < 1:
      t=t.replace(
        '<param name="moh-sound" value=""/>',
        '<param name="moh-sound" value=""/>\n      <param name="record-template" value="${record_path}/${record_name}"/>'
      )
    p.write_text(t, encoding="utf-8")
    subprocess.run(["docker","cp", str(p), "skykin-freeswitch:/etc/freeswitch/autoload_configs/callcenter.conf.xml"], check=True)
    Path("/opt/skykin/fs-live/callcenter.conf.xml").write_text(t, encoding="utf-8")
    print("callcenter record-template added")
  else:
    print("callcenter already has record-template")
PY

docker exec skykin-freeswitch fs_cli -x "reloadxml" || true
docker exec skykin-freeswitch fs_cli -x "reload mod_callcenter" || true
echo "VERIFY lua:"
docker exec skykin-freeswitch sh -c "grep -n 'api_on_answer\|execute_on_answer' /etc/freeswitch/scripts/skykin_inbound.lua | head -20"
docker exec skykin-freeswitch sh -c "ls -la /etc/freeswitch/scripts/skykin_record_on_agent.lua"
echo "DONE — new inbound calls record conversation only (after agent answer)."
echo "Existing WAVs still contain IVR; only new calls are fixed."
